
services:
  mongo:
    image: mongo:5.0.10
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
    restart: always
    depends_on: 
      - mongo
    volumes:
      - ./application:/app/application
