# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy Render

on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          echo "Installing requirements..."
          pip install -r requirements.txt
          pip install pytest mongomock

      - name: Install and run Black
        run: |
            pip install black
            black .
          
      - name: Run tests
        run: make test
    
  deploy:
      needs: test
      runs-on: ubuntu-latest
      environment:
        name: production
      steps:
        - name: Deploy to Render
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            echo "Deploy URL: $DEPLOY_URL"
            curl "$DEPLOY_URL"

